[package]
name = "models"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
structures = {workspace = true}
surrealdb = "2.2.1"
serde = { workspace = true, features = ["derive"] }
storage-finder = {workspace = true}

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
