[package]
name = "models"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
structures = {workspace = true}
surrealdb = "2.2.1"
serde = { version = "1.0.219", features = ["derive"] }