[package]
name = "fandom"
version.workspace = true
edition.workspace = true

[dependencies]
metadata-provider.workspace = true
scraper.workspace = true

[dev-dependencies]
tokio = {workspace = true, features = ["macros", "rt-multi-thread"]}
