[package]
name = "thetvdb"
version.workspace = true
edition.workspace = true

[dependencies]
metadata-provider = {workspace = true}
reqwest = {version = "0.12", features = ["json", "blocking"]}
serde_json = "1"
serde = {workspace = true, features = ["derive"]}
