[package]
name = "anilist"
version.workspace = true
edition.workspace = true

[dependencies]
metadata-provider = {workspace = true}
serde_json = "1.0"
serde = {workspace = true, features = ["derive"]}

[dev-dependencies]
tokio = {workspace = true, features = ["macros", "rt-multi-thread"]}
