[package]
name = "fill-db"
version.workspace = true
edition.workspace = true

[dependencies]
models = {workspace = true}
tokio = {workspace = true, features = ["macros", "rt-multi-thread"]}
dirs = "6.0.0"
serde_json = "1.0.140"
storage-finder = {workspace = true}